spring:
  datasource:
    url: "jdbc:mysql://servidorbasededatos1.mysql.database.azure.com:3306/testdb?useSSL=false"
    username: "danielmp599@servidorbasededatos1"
    
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        ddl-auto: update
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

app:
  jwtSecret: "PrivateKeyasdjklsakjkldjaslkjdlkasjdlkjaslkdjaslkjdlkjaslkdjklsajdkljaslk"
  jwtExpirationMs: 86400000
