spring:
  datasource:
    url: "jdbc:sqlserver://$AZ_DATABASE_NAME.database.windows.net:1433;database=demo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
    username: "spring@$AZ_DATABASE_NAME"
    password: "$AZ_SQL_SERVER_PASSWORD"
    
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        ddl-auto: update
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

app:
  jwtSecret: "PrivateKeyasdjklsakjkldjaslkjdlkasjdlkjaslkdjaslkjdlkjaslkdjklsajdkljaslk"
  jwtExpirationMs: 86400000
